export const websiteLink = '#';
export const tgLink = 'https://t.me/foxxyeth';
export const xLink = 'https://x.com/foxxyeth';
export const dexScreenerLink = '#';
export const dexToolsLink = '#';
export const uniSwapLink = '#';
export const buySellTax = '0%';
export const supply = '420.69 Billion tokens';
export const CA = 'TBA';
