export const websiteLink = 'https://kaboruto.com/';
export const tgLink = 'https://t.me/Kaborutomeme';
export const xLink = 'https://x.com/Kaborutomeme';
export const dexScreenerLink = '#';
export const dexToolsLink = '#';
export const uniSwapLink = '#';
export const buySellTax = '0/0';
export const supply = '1 Billion';
export const CA = 'TBA';
